#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 17 10:26:06 2023

@author: julian
"""

from preguntas_opciones import *
from generarEspeciales import armarEncuesta
def generarTrackingDiario(nombreEncuesta, rutaArchivos,rutaDocx,nombre_tsv =   'cuestionario.tsv', checkCarpeta = True):
    armarEncuesta(nombreEncuesta)
    cuestionarioTSV(ruta_cuestionario, ruta_trabajo, nombre_tsv, checkCarpeta = checkCarpeta)

sufijo = 'A'

trackings = ['NACIONAL', 'PBA', 'CABA']
rutaTrabajo = '/home/julian/trabajo/updates/corte 217/'
for tracking in trackings:
    nombreEncuesta = 'TRACKING_'+tracking+'_'+sufijo
    rutaArchivos = os.path.join(rutaTrabajo, 'web',tracking.lower())
    generarTrackingDiario(nombreEncuesta, rutaArchivos, rutaDocx)