textosESCOBAR_1 = {
    'encuesta_especial': "Municipio de Escobar - Noviembre",
	'bajada_encuesta_especial': "Encuesta Sincrónica",
    'bajada_encuesta_especial_fecha': "15/11/2022",
	'cruce': 'Cruce con otras preguntas:',
	'tituloDato1': 'Población objeto de estudio',
	'textoDato1': 'Población mayor de 16 años.',
	'tituloDato2': 'Unidad de muestreo',
    'textoDato2': 'Télefonos celulares de empresas Personal, Movistar y Claro, complementados con un 13% de teléfonos fijos para optimizar cobertura geográfica.',
	'tituloDato3': 'Ámbito',
	'textoDato3': 'Municipio de Escobar',
	'tituloDato4': 'Estratificación',
	'textoDato4': '',
	'tituloDato5': 'Técnicas de recolección de información',
	'textoDato5': 'Encuesta Automática (IVR) a teléfonos móviles y complementariamente a fijos.',
	'tituloDato6': 'Diseño muestral',
	'textoDato6': 'Muestreo aleatorio estratificado por localidad. La probabilidad de selección hacia el interior de cada estrato se definió de manera proporcional al tamaño de la localidad.',
	'tituloDato7': 'Tamaño muestral',
	'textoDato7': 'La captura de datos se llevó a cabo del día 09/11/2022 al 14/11/2022 abarcando 648 casos efectivos, 1.024 casos totales *no se registra sesgo significativo en la tasa de no respuesta.',
	'tituloDato8': 'Calibración de la muestra',
	'textoDato8': 'En función de datos paramétricos censales de sexo, edad y nivel educativo.',
	'tituloDato9': 'Margen de error',
	'textoDato9': '+/- 4.32%',

	'seleccioneFigura': 'Seleccione qué dirigentes o funcionarios políticos comparar:',
	'pregunta_imagen': '¿Qué imagen tiene de cada uno de estos políticos?',
	'labelimagen1': 'Imágen comparada, orden según imagen positiva',
	'labelimagen2': 'Imágen comparada, orden según ratio imagen positiva/negativa',
	'labelimagen3': 'Imágen comparada, orden según imagen negativa',

	'bloque1': 'Bloque Elecciones Municipales',
	'bloque1href': '/apps/bloque1',

	'bloque2': 'Reach de dirigentes locales',
	'bloque2href': '/apps/bloque2',

	'bloque4': 'Bloque Gestión Municipal',
	'bloque4href': '/apps/bloque4',

	'bloque3': 'Bloque Imágen de dirigentes',
	'bloque3href': '/apps/bloque3',

	'bloque5': 'Bloque Intención de voto',
	'bloque5href': '/apps/bloque5',



	'preguntaP05': 'En las elecciones generales a presidente del año 2019. ¿Recuerda usted a que candidatos votó?',
	'preguntaP06': '¿A cúal de los siguientes candidatos votó en las elecciones a intendente del año 2019?',
	'preguntaP07': 'Si las elecciones para intendente municipal fueran mañana ¿A qué espacio político votaría?',
	'preguntaP08': 'Pensando en las elecciones primarias (PASO) ¿A cúal de los siguientes candidatos preferiría votar para intendente? Escenario PASO 1',
	'preguntaP09': 'Pensando en las elecciones primarias (PASO) ¿A cúal de los siguientes candidatos preferiría votar para intendente? Escenario PASO 2',
	'preguntaP10': 'Si estos fueran los candidatos a intendente ¿A cúal preferiría votar? Escenario 1',
	'preguntaP11': 'Si estos fueran los candidatos a intendente ¿A cúal preferiría votar? Escenario 2',
	'preguntaP12': 'Si estos fueran los candidatos a intendente ¿A cúal preferiría votar? Escenario 3',
	'preguntaP13': 'Si estos fueran los candidatos a intendente ¿A cúal preferiría votar? Escenario 4',
	'preguntaP14': 'Si Ariel Sukarchuk fuese candidato a intendente, ud...',
	'preguntaP15': 'Si Roberto Costa fuese candidato a intendente, ud...',
	'preguntaP16': 'Si Mariano Castagnaro fuese candidato a intendente, ud...',
	'preguntaP17': 'Si Carlos "Beto" Ramil fuese candidato a intendente, ud...',
	'preguntaP18': 'Si Ricardo Choffi fuese candidato a intendente, ud...',
	'preguntaP19': 'Si Jésica Avejera fuese candidata a intendenta, ud...',
	'preguntaP20': 'Si Griselda Romariz fuese candidata a intendenta, ud...',
	'preguntaP21': '¿Qué evaluación hace ud de la actual gestión del intendente Ariel Sujarchuk?',
	'preguntaP22': 'Pensando en las próximas elecciones, ud. preferiría…',
	'preguntaP23': '¿Según su opinión, cúal es el área con mejor desempeño de la gestión municipal?',
	'preguntaP24': '¿Según su opinión, cúal es el área con peor desempeño de la gestión municipal?',
	'preguntaP25': 'De los siguientes servicios ¿Cúal considera necesario mejorar?',
	'preguntaP26': 'Según su opinión ¿Cúal es el principal problema de seguridad en el municipio?',
	'preguntaP27': '¿Qué imagen tiene de Ariel Sujarchuk?',
	'preguntaP28': '¿Qué imagen tiene de Roberto Costa?',
	'preguntaP29': '¿Qué imagen tiene de Mariano Castagnaro?',
	'preguntaP30': '¿Qué imagen tiene de Ricardo Choffi ?',
	'preguntaP31': '¿Qué imagen tiene de Jesica Avejera?',
	'preguntaP32': '¿Qué imagen tiene de Carlos “Beto” Ramil?',
	'preguntaP33': '¿Qué imagen tiene de Griselda Romariz?',
	'preguntaP34': '¿Qué imagen tiene de Leandro Costa?',
	'preguntaP35': '¿En las elecciones presidenciales del año que viene, al candidato de qué espacio político votaría?',
	'preguntaP37': '¿A cúal de los siguientes dirigentes del Frente de Todos y el peronismo preferiría ud. votar?',
	'preguntaP38': 'Y si en cambio, los candidatos del Frente de Todos y el peronismo fuesen los siguientes ¿A cúal preferiría ud. votar?',
	'preguntaP39': '¿A cúal de los siguientes dirigentes de Juntos por el cambio preferiría ud. votar?',
	'preguntaP40': '¿y si Milei se presentase a una interna de Juntos por el Cambio, lo votaría?',
	'preguntaP41': '¿Qué imagen tiene de Alberto Fernández?',
	'preguntaP42': '¿Qué imagen tiene de Mauricio Macri?',
	'preguntaP43': '¿Qué imagen tiene de CFK?',
	'preguntaP44': '¿Qué imagen tiene de Horacio Rodriguez Larreta?',
	'preguntaP45': '¿Qué imagen tiene de Sergio Massa?',
	'preguntaP46': '¿Qué imagen tiene de Patricia Bullrich?',
	'preguntaP47': '¿Qué imagen tiene de Javier Milei?',


	'labelP05': 'Voto presidente 2019',
	'labelP06': 'Voto intendente 2019',
	'labelP07': 'Intención de voto intendente',
	'labelP08': 'Escenario 1 PASO',
	'labelP09': 'Escenario 2 PASO',
	'labelP10': 'Escenario 1 Elecciones a intendente',
	'labelP11': 'Escenario 2 Elecciones a intendente',
	'labelP12': 'Escenario 3 Elecciones a intendente',
	'labelP13': 'Escenario 4 Elecciones a intendente',
	'labelP14': 'Preferencia de voto Ariel Sujarchuk',
	'labelP15': 'Preferencia de voto a Roberto Costa',
	'labelP16': 'Preferencia de voto a Mariano Castagnaro',
	'labelP17': 'Preferencia de voto a Carlos "Beto" Ramil',
	'labelP18': 'Preferencia de voto a Ricardo Choffi',
	'labelP19': 'Preferencia de voto a Jésica Avejera',
	'labelP20': 'Preferencia de voto a Griselda Romariz',
	'labelP21': 'Evaluación intendente Ariel Sujarchuk',
	'labelP22': 'Preferencia de continuidad de Ariel Sujarchuk',
	'labelP23': 'Área con mejor desempeño',
	'labelP24': 'Área con peor desempeño',
	'labelP25': 'Servicios a mejorar',
	'labelP26': 'Principal problema de seguridad',
	'labelP27': 'Imágen de Ariel Sujarchuk',
	'labelP28': 'Imágen de Roberto Costa',
	'labelP29': 'Imágen de Mariano Castagnaro',
	'labelP30': 'Imágen de Ricardo Choffi',
	'labelP31': 'Imágen de Jésica Avejera',
	'labelP32': 'Imágen de Carlos "Beto" Ramil',
	'labelP33': 'Imágen de Griselda Romariz',
	'labelP34': 'Imágen de Leandro Costa',
	'labelP35': 'Espacio político 2023 para presidente',
	'labelP37': 'Preferencia de candidato del Frente de Todos (sólo a los que dijeron votar al Frente de Todos)',
	'labelP38': 'Preferencia de candidato del Frente de Todos (sólo a los que dijeron votar al Frente de Todos)',
	'labelP39': 'Preferencia de candidato de JxC (sólo a los que dijeron votar a JxC)',
	'labelP40': 'Preferencia de voto a Javier Milei en interna de JxC (sólo a los que dijeron votar a JxC)',
	'labelP41': 'Imágen de Alberto Fernández',
	'labelP42': 'Imágen de Mauricio Macri',
	'labelP43': 'Imágen de CFK',
	'labelP44': 'Imágen de Horacio Rodriguez Larreta',
	'labelP45': 'Imágen de Sergio Massa',
	'labelP46': 'Imágen de Patricia Bullrich',
	'labelP47': 'Imágen de Javier Milei',








}

