import importlib

#'TRANSPORTE_1',

titulos = ['RIO_NEGRO_9',
           'NEUQUEN_14',
           'RIO_NEGRO_8',
           'RIO_NEGRO_8_bariloche',
           'RIO_NEGRO_8_cipoletti',
            'RIO_NEGRO_8_roca',
           'RIO_NEGRO_8_viedma',
           'TRACKING_NACIONAL_237',
           'CORRIENTES',
           'NEUQUEN_13',
           'RIO_NEGRO_7',
           'RIO_NEGRO_7_bariloche',
           'RIO_NEGRO_7_roca',
           'NEUQUEN_12',
           'RIOCUARTO',
           'LEY_OMNIBUS_2_convoto',
           'LEY_OMNIBUS_2',
           'NEUQUEN_11',
           'LEY_OMNIBUS',
           'MEDICOS_01',
           'NEUQUEN_10',
           'NEUQUEN_9',
           'APOYO_LULA',
           'GRUPOS_BLANCOYNULO',
            'GRUPOS_BLANCOPASO',
            'GRUPOS_BULLRICH',
            'GRUPOS_GRABOIS','GRUPOS_LARRETA','GRUPOS_SCHIARETTI',
           'TRACKING_NACIONAL_F',
           'TRACKING_PBA_F','TRACKING_CABA_F',
           'TRACKING_NACIONAL_E','TRACKING_PBA_E','TRACKING_CABA_E',
           'TARIFAS',
           'TRACKING_NACIONAL_D','TRACKING_PBA_D','TRACKING_CABA_D',
           'TIGRE_16',
           'TRACKING_NACIONAL_C','TRACKING_PBA_C','TRACKING_CABA_C',
           'TRACKING_NACIONAL_B','TRACKING_PBA_B','TRACKING_CABA_B',
           'TRACKING_NACIONAL_A','TRACKING_PBA_A','TRACKING_CABA_A',
            'BASE_1', # template para futuras encuestas
            #  'TRACKING_NACIONAL',# Prueba para ir pasando los trackings a la misma logica de las nuevas encuestas
                        ]
especiales_encuestas = titulos[:25]
especiales_layouts_dict = { encuesta:importlib.import_module(f"especiales.{encuesta}.apps.portada{encuesta}").layout
                           for encuesta in especiales_encuestas}


especiales_labels = {'RIO_NEGRO_9': 'prov',
                     'NEUQUEN_14':'Posicionamiento Político - Neuquén, Abril 2024',
                     'RIO_NEGRO_8':'Posicionamiento Político - Rio Negro, Abril 2024',
                    'RIO_NEGRO_8_bariloche': 'Posicionamiento Político - Rio Negro (Bariloche), Abril 2024',
                     'RIO_NEGRO_8_cipoletti': 'Posicionamiento Político - Rio Negro (Cipoletti), Abril 2024',
                    'RIO_NEGRO_8_roca': 'Posicionamiento Político - Rio Negro (Roca), Abril 2024',
                     'RIO_NEGRO_8_viedma': 'Posicionamiento Político - Rio Negro (Viedma), Abril 2024',
                     'TRACKING_NACIONAL_237': 'tracking',
                     'CORRIENTES':'Posicionamiento Político: Elecciones a Gobernador de Corrientes - Marzo 2024',
                     'NEUQUEN_13': 'Posicionamiento Político - Neuquén, Marzo 2024',
                     'RIO_NEGRO_7':'Posicionamiento Político - Rio Negro, Marzo 2024',
                     'RIO_NEGRO_7_bariloche':'Posicionamiento Político - Bariloche, Rio Negro, Marzo 2024',
                     'RIO_NEGRO_7_roca':'Posicionamiento Político - General Roca, Rio Negro, Marzo 2024',
                     'NEUQUEN_12': 'Posicionamiento Político - Neuquén, Febrero 2024 BIS',
                     'RIOCUARTO': 'Posicionamiento Político: Río Cuarto - Córdoba, Febrero 2024',
                     'LEY_OMNIBUS_2_convoto':'Encuesta Nacional: Opinión sobre la Ley Ómnibus (Raking con voto anterior) - Febrero 2024 (Corte Nº2)',
                     'LEY_OMNIBUS_2':'Encuesta Nacional: Opinión sobre la Ley Ómnibus (Raking sin voto anterior) - Febrero 2024 (Corte Nº2)',
                     'NEUQUEN_11' : 'Posicionamiento Político - Neuquén, Febrero 2024',
                     'LEY_OMNIBUS':'Encuesta Nacional: Opinión sobre la Ley Ómnibus - Febrero 2024',
                     'MEDICOS_01': 'Encuesta Nacional Médicos COVID 19 - Febrero 2024',
                     'NEUQUEN_10' : 'Posicionamiento Político - Neuquén, Enero 2024 (Corte Nº2)',
                     'NEUQUEN_9' : 'Posicionamiento Político - Neuquén, Enero 2024',
                     'APOYO_LULA' :'Posicionamiento político: Lula y el Ballotage 2023',
                     'TRACKING_ENTRESEMANA_1': 'Tracking Nacional - Corte especial: Modelo 1',
                     'TRACKING_ENTRESEMANA_2': 'Tracking Nacional - Corte especial: Modelo 2',
                     'TRACKING_ENTRESEMANA_3': 'Tracking Nacional - Corte especial: Modelo 3',
                     'TRACKING_ENTRESEMANA_4': 'Tracking Nacional - Corte especial: Modelo 4',
                     'TRACKING_ENTRESEMANA_5': 'Tracking Nacional - Corte especial: Modelo 5',
                     'TRACKING_ENTRESEMANA_PROMEDIO': 'Tracking Nacional - Corte especial: Promedio',
                     'GRUPOS_BLANCOYNULO' : 'Muestra Focal Probabilística - Votantes indecisos o con intención de voto en blanco en balotage',
                     'GRUPOS_BLANCOPASO':'Muestra Focal Probabilística - Voto en blanco en elecciones primarias y generales',
                     'GRUPOS_BULLRICH': 'Muestra Focal Probabilística - Votantes de P. Bullrich en elecciones primarias y generales',
                     'GRUPOS_GRABOIS':'Muestra Focal Probabilística - Votantes de J. Grabois',
                     'GRUPOS_LARRETA':'Muestra Focal Probabilística - Votantes de H. R. Larreta',
                     'GRUPOS_SCHIARETTI':'Muestra Focal Probabilística - Votantes de J. Schiaretti',
                     'TRACKING_NACIONAL_F' : 'Tracking Nacional (Estimación especial dos días)',
                     'TRACKING_PBA_F': 'Tracking PBA (Estimación especial dos días)',
                     'TRACKING_CABA_F' : 'Tracking CABA (Estimación especial dos días)',
                     'TRACKING_NACIONAL_E' : 'Tracking Nacional - Corte E',
                     'TRACKING_PBA_E': 'Tracking PBA - Corte E',
                     'TRACKING_CABA_E' : 'Tracking CABA - Corte E',
                     'TARIFAS' : 'Encuesta Nacional: Economía y Tarifas de Servicios públicos',
                     'TRACKING_NACIONAL_D' : 'Tracking Nacional - Corte D',
                     'TRACKING_PBA_D': 'Tracking PBA - Corte D',
                     'TRACKING_CABA_D' : 'Tracking CABA - Corte D',
                     'TIGRE_16':'Preferencias electorales: Elecciones Presidenciales, a Gobernador e Intendente - Municipio de Tigre, Octubre 2023',
                     'TRACKING_NACIONAL_C' : 'Tracking Nacional - Corte C',
                     'TRACKING_PBA_C': 'Tracking PBA - Corte C',
                     'TRACKING_CABA_C' : 'Tracking CABA - Corte C',
                     'TRACKING_NACIONAL_B' : 'Tracking Nacional - Corte B',
                     'TRACKING_PBA_B': 'Tracking PBA - Corte B',
                     'TRACKING_CABA_B' : 'Tracking CABA - Corte B',
                     'TRACKING_NACIONAL_A' : 'Tracking Nacional - Corte A',
                     'TRACKING_PBA_A': 'Tracking PBA - Corte A',
                     'TRACKING_CABA_A' : 'Tracking CABA - Corte A',
                     'NEUQUEN_8': 'Preferencias Electorales: Elecciones Presidenciales y Diputados Nacionales - Neuquén, Octubre 2023',
                     'SAN_MARTIN_5': 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales, a Gobernador e Intendente - San Martín, Octubre 2023',
                     'INSEGURIDAD_3': 'Percepción de la Inseguridad - Encuesta Nacional, Octubre 2023',
'MERLO_12': 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales, a Gobernador e Intendente - Merlo, Octubre 2023',
                     'RIO_NEGRO_6' : 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales y Diputados - Río Negro, Octubre 2023',
                     'SAN_ISIDRO_2':'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales, a Gobernador e Intendente - San Isidro, Octubre 2023',
                     'SAN_LUIS_1':'Escenarios Electorales: Elecciones Presidenciales - San Luis, Septiembre 2023',
                     'POSICIONAMIENTO_ESPECIAL_CABA_6':'Encuesta especial sobre percepciones económicas - CABA, Septiembre 2023',
                     'POSICIONAMIENTO_ESPECIAL_PBA_6': 'Encuesta especial sobre percepciones económicas - PBA, Septiembre 2023',
'POSICIONAMIENTO_ESPECIAL_NACIONAL_6': 'Encuesta especial sobre percepciones económicas - Nación, Septiembre 2023',
                     'ENTRE_RIOS_2': 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales y a Gobernador - Entre Ríos, Septiembre 2023',
                     'MISIONES_1':'Escenarios Electorales: Elecciones Presidenciales - Misiones, Septiembre 2023',
                     'CORDOBA_1':'Escenarios Electorales: Elecciones Presidenciales - Córdoba, Septiembre 2023',
                     'JUJUY_1': 'Escenarios Electorales: Elecciones Presidenciales - Jujuy, Septiembre 2023',
                     'NEUQUEN_7': 'Preferencias Electorales: Elecciones Presidenciales y Diputados Nacionales- Neuquén, Septiembre 2023',
                     'CHACO' : 'Escenarios Electorales: Elecciones a Gobernador - Chaco, Septiembre 2023',
                     'SANTA_FE_3': 'Escenarios Electorales: Elecciones a Gobernador - Santa Fé, Septiembre 2023 (Corte 2)',
                     'MENDOZA_2': 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales y a Gobernador - Mendoza, Agosto 2023',
                     'INSEGURIDAD_2': 'Percepción de la Inseguridad - Encuesta Nacional, Septiembre 2023',
                     'MERLO_11' : 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales, a Gobernador e Intendente - Merlo, Agosto 2023',
                     'SAN_MARTIN_4': 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales, a Gobernador e Intendente - San Martín, Agosto 2023',
                     'SANTA_FE_2':'Escenarios Electorales: Elecciones a Intendente - Rosario. Septiembre 2023',
                     'RIO_NEGRO_5': 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales y Diputados Río Negro - Agosto 2023 (corte 5)',
                     'POSICIONAMIENTO_ESPECIAL_NACIONAL_5':'Posicionamiento Político y Preferencias Electorales: Elecciones presidenciales - Nación Corte 5, Agosto 2023',
                     'POSICIONAMIENTO_ESPECIAL_CABA_5': 'Posicionamiento politico y preferencias electorales: Elecciones presidenciales y a Jefe de Gobeierno- CABA Corte 5, Agosto 2023',
                    'POSICIONAMIENTO_ESPECIAL_PBA_5': 'Posicionamiento Político y Preferencias Electorales: Elecciones presidenciales y a Gobernador - PBA Corte 5, Agosto 2023',
                     'TRACKING_DIARIO_CABA':'Informe Diario: Ciudad de Buenos Aires.',
                     'TRACKING_DIARIO_PBA':'Informe Diario: Provincia de Buenos Aires',
                     'TRACKING_DIARIO_NACIONAL': 'Informe Diario Nacional',
                     'TIGRE_15': "Preferencias electorales: Elecciones a Intendente y PASO - Municipio de Tigre, Agosto 2023",
                     'ENTRE_RIOS_1' : 'Posicionamiento político y preferencias electorales Entre Ríos - Agosto 2023',
                     'RIO_NEGRO_4': 'Posicionamiento Político y Preferencias Electorales: Elecciones Presidenciales y Diputados Río Negro - Agosto 2023 (corte 4)',
                     'POSICIONAMIENTO_ESPECIAL_PBA_3':'Posicionamiento Político y Preferencias Electorales: Elecciones presidenciales y a Gobernador - PBA Corte 3, Julio 2023',
                    'POSICIONAMIENTO_ESPECIAL_NACIONAL_3':'Posicionamiento Político y Preferencias Electorales: Elecciones presidenciales - Nación Corte 3, Julio 2023',
                    'POSICIONAMIENTO_ESPECIAL_CABA_3': 'Posicionamiento politico y preferencias electorales: Elecciones presidenciales y a Jefe de Gobeierno- CABA Corte 3, Julio 2023',
                     'MATANZA_1': 'Preferencias electorales: Elecciones a Intendente y PASO - La Matanza, Julio 2023',
                     'MORENO_1': 'Preferencias electorales: Elecciones a Intendente y PASO - Municipio de Moreno,  Julio 2023',
                     'CHUBUT_1':'Preferencias electorales: Elecciones a Gobernador - Chubut, Julio 2023',
                     'CBA_CAPITAL_1':'Preferencias electorales: Elecciones a Intendente y PASO - Ciudad de Córdoba,  Julio 2023',
                     'HURLINGHAM_3':'Preferencias electorales: Elecciones a Intendente y PASO - Hurlingham,  Julio 2023',
                     'SANTA_CRUZ_2': 'Preferencias electorales: Elecciones Presidenciales y a Gobernador 2023 - Provincia de Santa Cruz, Julio 2023',
                     'LAPLATA_1': 'Preferencias electorales: Elecciones generales La Plata 2023 - Julio 2023',
                    'NEUQUEN_6': 'Preferencias electorales: Elecciones Intendente Cutral Có 2023 - Corte 2 Julio 2023',
                     'SAN_MARTIN_3':'Preferencias electorales en elecciones generales 2023. Municipio de San Martín - Julio 2023',
                    'POSICIONAMIENTO_ESPECIAL_PBA_2':'Posicionamiento Político y Preferencias Electorales. Elecciones presidenciales y a Gobernador - PBA Julio 2023',
                     'POSICIONAMIENTO_ESPECIAL_NACIONAL_2':'Posicionamiento Político y Preferencias Electorales. Elecciones presidenciales - Nación Julio 2023',
                    'POSICIONAMIENTO_ESPECIAL_CABA_2':'Posicionamiento Político y Preferencias Electorales. Elecciones presidenciales y a Jefe de Gobierno - CABA Julio 2023',
                    'TIGRE_14': "Preferencias electorales en elecciones generales 2023. Municipio de Tigre - Julio 2023",
                    'MERLO_10': "Preferencias electorales: Elecciones intendente 2023 Merlo - Julio 2023",
                    'PLOTTIER_2':'Preferencias electorales: Elecciones intendente 2023 Plottier - Julio 2023',
                    'RIO_NEGRO_3': 'Posicionamiento político y preferencias electorales Río Negro - Julio 2023',
                    'SANTA_FE1_1': 'Preferencias electorales: Elecciones generales Santa Fé1 2023 - Julio 2023',
                    'SANTA_FE_1': 'Preferencias electorales: Elecciones generales Santa Fé 2023 - Julio 2023',
                    'NEUQUEN_5' :'Preferencias electorales: Elecciones Intendente Cutral Có 2023 - Julio 2023',
                    'ALIMENTACION_2' : 'Alimentación, salud y preferencias de consumo. Junio 2023',
                    'HURLINGHAM_2': 'Preferencias electorales en elecciones generales 2023. Municipio de Hurlingham - Corte 2, Junio 2023',
                    'POSICIONAMIENTO_CABA_14': 'Posicionamiento Político y Preferencias Electorales. Elecciones presidenciales y a Jefe de Gobierno - CABA Junio 2023',
                    'POSICIONAMIENTO_NACIONAL_12': 'Posicionamiento Político y Preferencias Electorales. Elecciones presidenciales - Nación Junio 2023',
                    'POSICIONAMIENTO_PBA_12': 'Posicionamiento Político y Preferencias Electorales. Elecciones presidenciales y a Gobernador - PBA Junio 2023',
                    'TIGRE_13': "Preferencias electorales en elecciones generales 2023. Municipio de Tigre - Junio 2023",
                    'HURLINGHAM_1':'Preferencias electorales en elecciones generales 2023. Municipio de Hurlingham - Junio 2023',
                    'INSEGURIDAD':'Percepción de la Inseguridad - Encuesta Nacional, Junio 2023',
                    'SAN_MARTIN_2': 'Preferencias electorales en elecciones generales 2023. Municipio de San Martín - Junio 2023',
                    'BASE_1': 'Plantilla de encuestas especiales',
                    # 'TRACKING_NACIONAL': 'Prueba de Tracking Nacional con Encuesta y Portada',
                    'POSICIONAMIENTO_PBA_11' : 'Posicionamiento politico y preferencias electorales. Elecciones Presidenciales y a Gobernador. Junio 2023',
                    'PPERON_3' : 'Preferencias electorales: Elecciones a intendente - Presidetnte Perón, Junio 2023',
                    'POSICIONAMIENTO_CBA_2':'Posicionamiento político y preferencias electorales: Elecciones 2023 Córdoba. Junio 2023',
                    'POSICIONAMIENTO_CABA_13':'Posicionamiento politico y preferencias electorales. Elecciones a Jefe de Gobierno. Junio 2023',
                    'NEUQUEN_4':'Elecciones intendente 2023 Rincón de Los Sauces. Junio 2023',
                    'POSICIONAMIENTO_NACIONAL_11': 'Posicionamiento politico y preferencias electorales, Elecciones presidenciales. Junio 2023',
                    'PLOTTIER_1':'Preferencias electorales: Elecciones intendente 2023 Plottier. Junio 2023',
                    'RIO_NEGRO_2':'Preferencias electorales: Elecciones intendente 2023 Bariloche. Junio 2023',
                    'VICEGOBERNADORES_PBA':'Preferencias electorales: candidatos a Vicegobernador de Provincia de Buenos Aires 2023. Junio 2023',
                    'TIGRE_12': "Preferencias electorales y opinión sobre la gestión municipal - Municipio de Tigre, Mayo 2023",
                    'MENDOZA_1': "Preferencias electorales: Elecciones a Gobernador 2023 Mendoza. Junio 2023",
                    'RIO_NEGRO_1': "Preferencias electorales: Elecciones intendente 2023 Cinco Saltos. Mayo 2023",
                    'ALIMENTACION_1' : 'Alimentación, salud y preferencias de consumo. Mayo 2023',
                    'MERLO_9': "Preferencias electorales: Elecciones intendente 2023 Merlo. Mayo 2023",
                    "POLITICA_ELECCIONES_1" : "Política, elecciones y participación ciudadana. Mayo 2023",
                    "FORMULAS_PRESIDENCIALES_1" : "Fórmulas presidenciales. Mayo 2023",
                    'AMBIENTE_1':"Medio Ambiente. Mayo 2023",
                    'MORON_1': "Preferencias electorales: Elecciones intendente 2023 Morón. Abril 2023",
                    'POSICIONAMIENTO_NACIONAL_10': 'Posicionamiento politico y preferencias electorales, Elecciones presidenciales. Mayo 2023',
                    'POSICIONAMIENTO_CABA_10': 'Posicionamiento politico y preferencias electorales, Elecciones a Jefe de Gobierno. CABA Mayo 2023',
                    'POSICIONAMIENTO_PBA_10': 'Posicionamiento politico y preferencias electorales, Elecciones presidenciales y a Gobernador. PBA Mayo 2023',
                    'POSICIONAMIENTO_NACIONAL_9': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Abril 2023',
                    'POSICIONAMIENTO_PBA_9': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Abril 2023',
                    'POSICIONAMIENTO_BA_2': 'Posicionamiento político y preferencias electorales: Elecciones PBA 2023. Abril 2023',
                    'ALQUILERES_NACIONAL_1':'Nueva Ley de Alquileres',
                    'ALQUILERES_PBA_1':'Alquileres PBA. Abril 2023',
                    'SANTA_CRUZ_1':'Preferencias electorales: Elecciones gobernador 2023 Santa Cruz. Marzo 2023',
                    'NEUQUEN_2':'Preferencias electorales: Elecciones gobernador 2023 Neuquén. Abril 2023',

                    'NEUQUEN_1':'Preferencias electorales: Elecciones gobernador 2023 Neuquén. Marzo 2023',
                    'POSICIONAMIENTO_CBA_1': 'Posicionamiento político y preferencias electorales: Elecciones 2023 Córdoba. Marzo 2023',
                    'POSICIONAMIENTO_CORDOBA_1': 'Posicionamiento político y preferencias electorales: Elecciones 2023 Córdoba. Marzo 2023',
                    'POSICIONAMIENTO_CABA_1': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 CABA. Marzo 2023',
                    'POSICIONAMIENTO_NACIONAL_8': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Febrero 2023',
                    'POSICIONAMIENTO_PBA_8': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Febrero 2023',
                    'POSICIONAMIENTO_NACIONAL_7': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Diciembre 2022',
                    'POSICIONAMIENTO_PBA_7': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Diciembre 2022',
                    'SAN_MARTIN_1':  "Municipio de San Martín - Febrero",
                    'MERLO_7':  "Municipio de Merlo - Diciembre",
                    'ESCOBAR_1':  "Municipio de Escobar - Noviembre",
                    'TIGRE_11': "Municipio de Tigre - Abril",
                    'TIGRE_10': "Municipio de Tigre - Diciembre/Enero",
                    'TIGRE_9':  "Municipio de Tigre - Octubre",
                    'BANCOS_2': 'ABAPRA',
                    'BANCOS_1':'Encuesta para primer Congreso Federal',
                    'GOB_PBA_1': 'Posicionamiento político y preferencias electorales: Elecciones gobernador 2023 PBA. Diciembre 2022',
                    'POSICIONAMIENTO_NACIONAL_6': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Noviembre 2022',
                    'POSICIONAMIENTO_PBA_6': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Noviembre 2022',
                    #    'POSICIONAMIENTO_NACIONAL_5': 'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Octubre 2022',

                    'POSICIONAMIENTO_NACIONAL_5':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Octubre 2022',
                    'POSICIONAMIENTO_PBA_5':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Octubre 2022',
                    'POSICIONAMIENTO_NACIONAL_4':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Septiembre 2022',
                    'POSICIONAMIENTO_PBA_4':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Septiembre 2022',
                    'POSICIONAMIENTO_NACIONAL_3':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Agosto 2022',
                    'POSICIONAMIENTO_PBA_3':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Agosto 2022',
                    'POSICIONAMIENTO_NACIONAL_2':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Julio 2022',
                    'POSICIONAMIENTO_PBA_2':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Julio 2022',
                    'POSICIONAMIENTO_NACIONAL_1':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 Nacional. Mayo 2022',
                    'POSICIONAMIENTO_PBA_1':'Posicionamiento político y preferencias electorales: Elecciones presidenciales 2023 PBA. Mayo 2022',
                    'PASO_BA': "Provincia de Buenos Aires 06/07/21",
                    'PASO2_BA': "Provincia de Buenos Aires 10/07/21",
                    'PASO_BA_3':  "Provincia de Buenos Aires 18/08/21",
                    'PASO_BA_4': "Provincia de Buenos Aires 23/08/21",
                    'PASO_BA_5': "Legislativa Provincia de Buenos Aires 19/09/21",
                    'LEG_PBA_2': "Legislativa Provincia de Buenos Aires 26/09/21",
                    'PPERON_1': "Municipio de Presidente Peron 21/08/21",
                    'PPERON_2': "Municipio de Presidente Peron 11/09/21",
                    'SANTIAGO': "Santiago del Estero 16/02/21",
                    'SANTIAGO2': "Santiago del Estero  17/07/21",
                    'SANTIAGO_3': "Santiago del Estero  12/08/21",
                    'TIGRE': "Municipio de Tigre 21/07/21",
                    'TIGRE_2': "Municipio de Tigre 10/08/21",
                    'TIGRE_3': "Municipio de Tigre 29/09/21",
                    'TIGRE_4': "Municipio de Tigre 28/10/21",
                    'TIGRE_5': "Municipio de Tigre 08/11/21",
                    'TIGRE_6': "Municipio de Tigre 27/06/22",
                    'TIGRE_7': "Municipio de Tigre 28/07/22",
                    'TIGRE_8': "Municipio de Tigre Agosto",
                    'SAN_ISIDRO_1': "Municipio de San Isidro 14/10/21",
                    'MERLO_1': "Municipio de Merlo 21/10/21",
                    'MERLO_2': "Municipio de Merlo 06/05/22",
                    'MERLO_3': "Municipio de Merlo - Junio",
                    'MERLO_4': "Municipio de Merlo - Julio",
                    'MERLO_5': "Municipio de Merlo - Agosto",
                    'MERLO_6': "Municipio de Merlo - Septiembre",
                    'MERLO_8': "Municipio de Merlo - Marzo",
                    'VACUNAS_1': "Combinaciones vacunales 30/10/2021"
        }
