textosBANCOS_2 = {
    'encuesta_especial': "ABAPRA",
	'bajada_encuesta_especial': "Encuesta Sincrónica",
    'bajada_encuesta_especial_fecha': "17/03/2023",
	'cruce': 'Cruce con otras preguntas:',
	'tituloDato1': 'Población objeto de estudio',
	'textoDato1': 'Población entre 18 y 26 años.',
	'tituloDato2': 'Unidad de muestreo',
	'textoDato2': 'Télefonos celulares de empresas Personal, Movistar y Claro, complementados con un 13% de teléfonos fijos para optimizar cobertura geográfica.',
	'tituloDato3': 'Ámbito',
	'textoDato3': 'República Argentina',
	'tituloDato4': 'Estratificación',
	'textoDato4': 'Cinco estratos regionales (NEA, NOA, Cuyo, Centro y Patagonia) y Cordones I,II y III de la RMBA e interior PBA.',
	'tituloDato5': 'Técnicas de recolección de información',
	'textoDato5': 'ES - Encuesta Sincrónica (IVR) a teléfonos móviles.',
	'tituloDato6': 'Diseño muestral',
	'textoDato6': 'Muestreo aleatorio estratificado por provincias, CABA, Cordones I, II y III de la RMBA e interior PBA. La probabilidad de selección hacia el interior de cada estrato se definió de manera proporcional al tamaño del departamento.',
	'tituloDato7': 'Tamaño muestral',
	'textoDato7': 'La captura de datos se llevó a cabo los días 16/03/2023 y 17/03/2023 abarcando 5.394 casos efectivos.',
	'tituloDato8': 'Calibración de la muestra',
	'textoDato8': 'En función de datos paramétricos censales de sexo, edad y nivel educativo.',
	'tituloDato9': 'Margen de error',
	'textoDato9': '+/- 1.13% (Bloque crédito: 2.79%, Bloque emprendedores: 2.96%)',

	'seleccioneFigura': 'Seleccione qué dirigentes o funcionarios políticos comparar:',
	'pregunta_imagen': '¿Qué imagen tiene de cada uno de estos políticos?',
	'labelimagen1': 'Imágen comparada, orden según imagen positiva',
	'labelimagen2': 'Imágen comparada, orden según ratio imagen positiva/negativa',
	'labelimagen3': 'Imágen comparada, orden según imagen negativa',

	'bloque0': 'Perfil Socioecónomico',
	'bloque0href': '/apps/bloque0',
	'bloque1': 'Bloque Acceso al crédito',
	'bloque1href': '/apps/bloque1',
	'bloque2': 'Bloque Emprendedores',
	'bloque2href': '/apps/bloque2',


}


textosBANCOS_2.update(
{
'preguntaP02': 'Por favor indique su género',
'labelP02': 'Género',
'preguntaP03': '¿Cúal es su estado civil?',
'labelP03': 'Estado civil',
'preguntaP04': '¿Tiene hijos?',
'labelP04': 'Hijos',
'preguntaP06': '¿Podría indicarnos cuál es su situación laboral en la actualidad?',
'labelP06': 'Situación laboral actual',
'preguntaP07': '¿Tiene algún emprendimiento comercial propio o microempresa actualmente?',
'labelP07': 'Emprendimientos',
'preguntaP08': '¿Cúales son sus ingresos mensuales?',
'labelP08': 'Ingresos mensuales',
'preguntaP09': '¿En los últimos 5 años solicitó alguna línea de crédito en alguna entidad financiera?',
'labelP09': 'Solicitud de créditos en los últimos 5 años',
'preguntaP10': '¿Principalmente por qué razón no ha solicitado un préstamo en los últimos 5 años? (Solo para quienes no hayan solicitado un préstamo en los últimos 5 años)',
'labelP10': 'Razón de la no solicitud de créditos (Para quienes no hayan solicitado préstamo)',
'preguntaP11': 'Pensando en el último préstamo solicitado ¿En qué tipo de entidad gestionó la línea de crédito? (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'labelP11': 'Tipo de entidad gestora de créditos  (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'preguntaP12': 'Si tuviera que definir el monto del crédito solicitado en la actualidad ¿Aproximadamente de cuanto sería? (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'labelP12': 'Monto del crédito (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'preguntaP13': '¿Tuvo algún problema o dificultad durante el proceso de gestión del crédito? (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'labelP13': 'Dificultades en el proceso de gestión del crédito (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'preguntaP14': '¿Ha sentido algún trato diferencial durante la gestión del crédito debido a su género? (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'labelP14': 'Trato diferencial en la gestión del crédito debido al género (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'preguntaP15': '¿El crédito solicitado le fue fue otorgado? (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',
'labelP15': 'Otorgamiento del crédito solicitado (Solo para quienes hayan solicitado un préstamo en los últimos 5 años)',

'preguntaP16': '¿Ha recibido alguna vez capacitación o asesoramiento financiero para mejorar sus habilidades de gestión financiera? (Solo para quienes dijeron tener un emprendimiento o microempresa)',
'labelP16': 'Capacitacion financiera (Solo para quienes dijeron tener un emprendimiento o microempresa)',
'preguntaP17': '¿En alguna oportunidad recibió apoyo financiero por parte de una organización no gubernamental para emprendedores? (Solo para quienes dijeron tener un emprendimiento o microempresa)',
'labelP17': 'Apoyo financiero de ONGs para emprendedores (Solo para quienes dijeron tener un emprendimiento o microempresa)',
'preguntaP18': 'Si hoy en día tuviera la posibilidad de acceder a un crédito ¿Cuál es la cantidad de dinero que necesitaría para invertir en su emprendimiento? (Solo para quienes dijeron tener un emprendimiento o microempresa))',
'labelP18': 'Monto necesario para invertir (Solo para quienes dijeron tener un emprendimiento o microempresa)'}
)